# Generated by Django 3.1.4 on 2020-12-26 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20201215_0841'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='doc_num',
            field=models.CharField(default='', max_length=12, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='document',
            name='dtype',
            field=models.CharField(choices=[('PP', 'passport'), ('OT', 'Others'), ('ID', 'Identity card')], max_length=2),
        ),
    ]
